project_id = "vpanwarxvueuylfnipmd"

[functions.notify-nearby-report]
verify_jwt = true

[functions.notify-responder-coming]
verify_jwt = true

[functions.notify-quake-damage]
verify_jwt = true

[functions.notify-trip-update]
verify_jwt = true

[functions.send-message-push]
verify_jwt = true

[functions.send-web-push]
verify_jwt = true

[functions.check-delayed-trips]
verify_jwt = false

[functions.notify-alert-resolved]
verify_jwt = true

[functions.register-with-invite]
verify_jwt = false

[functions.fetch-rss-news]
verify_jwt = false

[functions.notify-app-update]
verify_jwt = false
