project_id = "vpanwarxvueuylfnipmd"

[functions.notify-nearby-report]
verify_jwt = true

[functions.notify-responder-coming]
verify_jwt = true

[functions.notify-quake-damage]
verify_jwt = true

[functions.notify-trip-update]
verify_jwt = true

[functions.send-message-push]
verify_jwt = true

[functions.send-web-push]
verify_jwt = true

[functions.check-delayed-trips]
verify_jwt = false

[functions.notify-alert-resolved]
verify_jwt = false

[functions.notify-panic-broadcast]
verify_jwt = false

[functions.register-with-invite]
verify_jwt = false

[functions.fetch-rss-news]
verify_jwt = false

[functions.notify-app-update]
verify_jwt = false

[functions.fetch-fires]
verify_jwt = false

[functions.fetch-ssn]
verify_jwt = false

[functions.remind-incomplete-profiles]
verify_jwt = false

[functions.fetch-skyalert]
verify_jwt = false

[functions.send-drill-notifications]
verify_jwt = false

[functions.trigger-drill-alert]
verify_jwt = false

[functions.force-update-email]
verify_jwt = false

[functions.fetch-ssn-rss]
verify_jwt = false

[functions.push-overdue-trips]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.notify-clave100-chat]
verify_jwt = false

[functions.fetch-smn-alerts]
verify_jwt = false

[functions.fetch-owm-weather]
verify_jwt = false

[functions.get-shared-trip]
verify_jwt = false

[functions.notify-responder-contact]
verify_jwt = false
