project_id = "vpanwarxvueuylfnipmd"

[functions.notify-nearby-report]
verify_jwt = true

[functions.notify-responder-coming]
verify_jwt = false

[functions.notify-quake-damage]
verify_jwt = false

[functions.notify-trip-update]
verify_jwt = false

[functions.send-message-push]
verify_jwt = false
