// Catálogo de cámaras verificadas — v3
// Fuentes: YouTube
// Última actualización: marzo 2026

import { Camera, LayoutOption } from './types';

const YT_PARAMS = '?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0&iv_load_policy=3&playsinline=1';

export const DEFAULT_CAMERAS: Camera[] = [
  // ═══════════════════════════════════════
  // México
  // ═══════════════════════════════════════
  {
    id: 'yt-cdmx-ref',
    name: 'Ciudad de México',
    city: 'CDMX',
    country: 'México',
    description: 'Ciudad de México en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/yyWbHA_EWCc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-zocalo2',
    name: 'Zócalo CDMX EN VIVO',
    city: 'CDMX',
    country: 'México',
    description: 'Zócalo de la Ciudad de México en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/iFk6nRCYOd0${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-tlamacas-popo',
    name: 'Tlamacas, Popocatépetl',
    city: 'Popocatépetl',
    country: 'México',
    description: 'Vista desde Tlamacas del volcán Popocatépetl',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/NI4v1OlIlZM${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-aicm-live',
    name: 'AICM En Vivo',
    city: 'CDMX',
    country: 'México',
    description: 'Aeropuerto Internacional de la Ciudad de México en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/mCyFwnCcZJk${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-basilica-guadalupe',
    name: 'Basílica de Guadalupe, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Basílica de Guadalupe en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/FgGBtXzjqkA${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-bellas-artes',
    name: 'Bellas Artes, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Palacio de Bellas Artes en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/fiUMCo3d9nU${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cancun-park-royal',
    name: 'Cancún, Hotel Park Royal Beach',
    city: 'Cancún',
    country: 'México',
    description: 'Cancún Hotel Park Royal Beach en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/2Yq0hv2tZM8${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-torre-latino-sur',
    name: 'CDMX Vista Sur Torre Latino',
    city: 'CDMX',
    country: 'México',
    description: 'Vista sur desde la Torre Latinoamericana',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OwW-Zr4OK3k${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-torre-latino-poniente',
    name: 'CDMX Torre Latino Oeste',
    city: 'CDMX',
    country: 'México',
    description: 'Vista oeste desde la Torre Latinoamericana',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/CsWJN_OgxwE${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-pachuca',
    name: 'Pachuca, Hidalgo',
    city: 'Pachuca',
    country: 'México',
    description: 'Pachuca, Hidalgo en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/levojxrvxQI${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-popo-altzomoni',
    name: 'Popocatépetl, Altzomoni',
    city: 'Popocatépetl',
    country: 'México',
    description: 'Vista desde Altzomoni del volcán Popocatépetl',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/rayKu7F6Ub4${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-ixtapa-zihua',
    name: 'Ixtapa Zihuatanejo, Gro.',
    city: 'Ixtapa Zihuatanejo',
    country: 'México',
    description: 'Ixtapa Zihuatanejo en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/ZmGJecDmuiY${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-garibaldi-cdmx',
    name: 'Garibaldi, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Plaza Garibaldi en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/nM4I71den9Q${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-chihuahua-puente',
    name: 'Chihuahua Puente Internacional',
    city: 'Ciudad Juárez',
    country: 'México',
    description: 'Puente Internacional Paso del Norte en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/0Pg3S6s76IE${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-marina-acapulco',
    name: 'Marina Acapulco, Guerrero',
    city: 'Acapulco',
    country: 'México',
    description: 'Marina de Acapulco, Guerrero en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/9f3npaKdyCA${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-reforma-cdmx',
    name: 'Reforma, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Paseo de la Reforma en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OvFdu7dDVi8${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-monumento-revolucion-cdmx',
    name: 'Monumento a la Revolución, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Monumento a la Revolución en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/J7jgTmCemgc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-queretaro-plaza-armas',
    name: 'Querétaro, Plaza de Armas',
    city: 'Querétaro',
    country: 'México',
    description: 'Plaza de Armas de Querétaro en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/u5y5G8gastI${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-queretaro-5-febrero',
    name: 'Av. 5 de Febrero, Querétaro',
    city: 'Querétaro',
    country: 'México',
    description: 'Avenida 5 de Febrero en Querétaro en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/qnoibFINZAw${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-nuevo-vallarta',
    name: 'Nuevo Vallarta, Nayarit',
    city: 'Nuevo Vallarta',
    country: 'México',
    description: 'Nuevo Vallarta, Nayarit en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/A59ctqhiVNc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-guadalajara-jalisco',
    name: 'Guadalajara, Vista Poniente',
    city: 'Guadalajara',
    country: 'México',
    description: 'Guadalajara vista poniente en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/SP0PzhBX1SE${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-puebla-puebla',
    name: 'Puebla, Pue.',
    city: 'Puebla',
    country: 'México',
    description: 'Puebla en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/VZcb6neiihI${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-volcan-colima',
    name: 'Volcán de Colima',
    city: 'Colima',
    country: 'México',
    description: 'Volcán de Colima en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/hKj918yyq10${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cozumel-quintana-roo',
    name: 'Cozumel, Quintana Roo',
    city: 'Cozumel',
    country: 'México',
    description: 'Cozumel, Quintana Roo en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OcS0DxGKjG4${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-mazatlan-sinaloa',
    name: 'Mazatlán, Sinaloa',
    city: 'Mazatlán',
    country: 'México',
    description: 'Mazatlán, Sinaloa en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/SWHJFE29Bo0${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cancun-poniente',
    name: 'Cancún, Quintana Roo hacia el Poniente',
    city: 'Cancún',
    country: 'México',
    description: 'Cancún hacia el poniente en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/AyVSlOI7c9Q${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-torre-latino-este',
    name: 'CDMX Torre Latino Este',
    city: 'CDMX',
    country: 'México',
    description: 'Vista este desde la Torre Latinoamericana',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/J0_rtFPD-oE${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-chapultepec',
    name: 'CDMX Bosque de Chapultepec',
    city: 'CDMX',
    country: 'México',
    description: 'Bosque de Chapultepec en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/SEmWKejE2Xg${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-tlalpan',
    name: 'CDMX, Centro Tlalpan',
    city: 'CDMX',
    country: 'México',
    description: 'Centro de Tlalpan en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/EaBdl4I887c${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-volcan-colima-palmillas',
    name: 'Volcán de Colima desde Palmillas',
    city: 'Colima',
    country: 'México',
    description: 'Volcán de Colima visto desde Palmillas',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/oC11QNM--hY${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-popo-amecameca',
    name: 'Volcán Popocatépetl desde Amecameca',
    city: 'Amecameca',
    country: 'México',
    description: 'Popocatépetl visto desde Amecameca',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/URhVB0yqOoc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-queretaro-panoramica',
    name: 'Querétaro, Panorámica',
    city: 'Querétaro',
    country: 'México',
    description: 'Vista panorámica de Querétaro',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/x1chHm_9HfA${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-tijuana-panoramica',
    name: 'Tijuana, Vista Panorámica',
    city: 'Tijuana',
    country: 'México',
    description: 'Vista panorámica de Tijuana',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/WcBxvZKxftM${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cancun-nichupte',
    name: 'Cancún, Laguna de Nichupté',
    city: 'Cancún',
    country: 'México',
    description: 'Laguna de Nichupté, Cancún en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/sV1FnrIukbQ${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-teotihuacan',
    name: 'Pirámides de Teotihuacán',
    city: 'Teotihuacán',
    country: 'México',
    description: 'Pirámides de Teotihuacán en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/QDDJabSPu70${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-hermosillo-panoramica',
    name: 'Hermosillo, Son. Panorámica',
    city: 'Hermosillo',
    country: 'México',
    description: 'Vista panorámica de Hermosillo, Sonora',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/z_I152IMqI8${YT_PARAMS}`,
    region: 'mexico',
  },
  // ═══════════════════════════════════════
  // Norteamérica
  // ═══════════════════════════════════════
  {
    id: 'yt-times-square',
    name: 'Times Square, NY',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Times Square en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/rnXIjl_Rzy4${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-washington-dc',
    name: 'Washington D.C.',
    city: 'Washington D.C.',
    country: 'EE.UU.',
    description: 'Washington D.C. en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/1wV9lLe14aU${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-white-house',
    name: 'White House, Washington D.C.',
    city: 'Washington D.C.',
    country: 'EE.UU.',
    description: 'Casa Blanca en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/Fu8vYoIkaeM${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-bryant-park',
    name: 'Bryant Park, New York',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Bryant Park en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/XDgu2VKXM3s${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-venice-beach',
    name: 'Venice Beach, CA',
    city: 'Los Ángeles',
    country: 'EE.UU.',
    description: 'Venice Beach en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/EO_1LWqsCNE${YT_PARAMS}`,
    region: 'northamerica',
  },
  // ═══════════════════════════════════════
  // Europa
  // ═══════════════════════════════════════
  {
    id: 'yt-paris',
    name: 'París, Francia',
    city: 'París',
    country: 'Francia',
    description: 'París en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OzYp4NRZlwQ${YT_PARAMS}`,
    region: 'europe',
  },
  // ═══════════════════════════════════════
  // Asia
  // ═══════════════════════════════════════
  {
    id: 'yt-tokyo',
    name: 'Tokio, Japón',
    city: 'Tokio',
    country: 'Japón',
    description: 'Tokio en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/_k-5U7IeK8g${YT_PARAMS}`,
    region: 'asia_mideast',
  },
  {
    id: 'yt-tokyo-odaiba',
    name: 'Tokio, Odaiba',
    city: 'Tokio',
    country: 'Japón',
    description: 'Odaiba, Tokio en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/ytXE2pk07dA${YT_PARAMS}`,
    region: 'asia_mideast',
  },
  // ═══════════════════════════════════════
  // Global
  // ═══════════════════════════════════════
];

// IDs de las 4 cámaras por defecto al abrir por primera vez
export const DEFAULT_INITIAL_CAMERA_IDS = [
  'yt-cdmx-torre-latino-sur',
  'yt-cdmx-torre-latino-poniente',
  'yt-bellas-artes',
  'yt-cdmx-zocalo2',
];

export const LAYOUT_OPTIONS: LayoutOption[] = [
  { type: '1x1', label: '1×1', cells: 1, icon: '⬜' },
  { type: '2x1', label: '2×1', cells: 2, icon: '▬' },
  { type: '2x2', label: '2×2', cells: 4, icon: '⊞' },
  { type: '1+2', label: '1+2', cells: 3, icon: '◧' },
  { type: '1+4', label: '1+4', cells: 5, icon: '◫' },
  { type: '3x3', label: '3×3', cells: 9, icon: '▦' },
];

export function getCellCount(layout: string): number {
  return LAYOUT_OPTIONS.find(l => l.type === layout)?.cells ?? 4;
}

export const REGION_LABELS: Record<string, string> = {
  mexico: '🇲🇽 México',
  latam: '🌎 América Latina',
  northamerica: '🇺🇸 Norteamérica',
  europe: '🇪🇺 Europa',
  asia_mideast: '🌏 Asia y Medio Oriente',
};
