// Catálogo de cámaras verificadas — v3
// Fuentes: YouTube
// Última actualización: marzo 2026

import { Camera, LayoutOption } from './types';

const YT_PARAMS = '?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0&iv_load_policy=3&playsinline=1';

export const DEFAULT_CAMERAS: Camera[] = [
  // ═══════════════════════════════════════
  // México
  // ═══════════════════════════════════════
  {
    id: 'yt-cdmx-ref',
    name: 'Ciudad de México',
    city: 'CDMX',
    country: 'México',
    description: 'Ciudad de México en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/yyWbHA_EWCc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-zocalo2',
    name: 'Zócalo CDMX EN VIVO',
    city: 'CDMX',
    country: 'México',
    description: 'Zócalo de la Ciudad de México en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/iFk6nRCYOd0${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-tlamacas-popo',
    name: 'Tlamacas, Popocatépetl',
    city: 'Popocatépetl',
    country: 'México',
    description: 'Vista desde Tlamacas del volcán Popocatépetl',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/NI4v1OlIlZM${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-aicm-live',
    name: 'AICM En Vivo',
    city: 'CDMX',
    country: 'México',
    description: 'Aeropuerto Internacional de la Ciudad de México en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/mCyFwnCcZJk${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-basilica-guadalupe',
    name: 'Basílica de Guadalupe, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Basílica de Guadalupe en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/FgGBtXzjqkA${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-bellas-artes',
    name: 'Bellas Artes, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Palacio de Bellas Artes en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/fiUMCo3d9nU${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cancun-park-royal',
    name: 'Cancún, Hotel Park Royal Beach',
    city: 'Cancún',
    country: 'México',
    description: 'Cancún Hotel Park Royal Beach en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/2Yq0hv2tZM8${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-torre-latino-sur',
    name: 'CDMX Vista Sur Torre Latino',
    city: 'CDMX',
    country: 'México',
    description: 'Vista sur desde la Torre Latinoamericana',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OwW-Zr4OK3k${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-torre-latino-poniente',
    name: 'CDMX Torre Latino Oeste',
    city: 'CDMX',
    country: 'México',
    description: 'Vista oeste desde la Torre Latinoamericana',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/CsWJN_OgxwE${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-pachuca',
    name: 'Pachuca, Hidalgo',
    city: 'Pachuca',
    country: 'México',
    description: 'Pachuca, Hidalgo en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/levojxrvxQI${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-popo-altzomoni',
    name: 'Popocatépetl, Altzomoni',
    city: 'Popocatépetl',
    country: 'México',
    description: 'Vista desde Altzomoni del volcán Popocatépetl',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/rayKu7F6Ub4${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-ixtapa-zihua',
    name: 'Ixtapa Zihuatanejo, Gro.',
    city: 'Ixtapa Zihuatanejo',
    country: 'México',
    description: 'Ixtapa Zihuatanejo en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/ZmGJecDmuiY${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-garibaldi-cdmx',
    name: 'Garibaldi, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Plaza Garibaldi en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/nM4I71den9Q${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-chihuahua-puente',
    name: 'Chihuahua Puente Internacional',
    city: 'Ciudad Juárez',
    country: 'México',
    description: 'Puente Internacional Paso del Norte en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/0Pg3S6s76IE${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-marina-acapulco',
    name: 'Marina Acapulco, Guerrero',
    city: 'Acapulco',
    country: 'México',
    description: 'Marina de Acapulco, Guerrero en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/9f3npaKdyCA${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-reforma-cdmx',
    name: 'Reforma, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Paseo de la Reforma en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OvFdu7dDVi8${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-monumento-revolucion-cdmx',
    name: 'Monumento a la Revolución, CDMX',
    city: 'CDMX',
    country: 'México',
    description: 'Monumento a la Revolución en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/J7jgTmCemgc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-queretaro-plaza-armas',
    name: 'Querétaro, Plaza de Armas',
    city: 'Querétaro',
    country: 'México',
    description: 'Plaza de Armas de Querétaro en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/u5y5G8gastI${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-queretaro-5-febrero',
    name: 'Av. 5 de Febrero, Querétaro',
    city: 'Querétaro',
    country: 'México',
    description: 'Avenida 5 de Febrero en Querétaro en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/qnoibFINZAw${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-nuevo-vallarta',
    name: 'Nuevo Vallarta, Nayarit',
    city: 'Nuevo Vallarta',
    country: 'México',
    description: 'Nuevo Vallarta, Nayarit en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/A59ctqhiVNc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-guadalajara-jalisco',
    name: 'Guadalajara, Vista Poniente',
    city: 'Guadalajara',
    country: 'México',
    description: 'Guadalajara vista poniente en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/SP0PzhBX1SE${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-puebla-puebla',
    name: 'Puebla, Pue.',
    city: 'Puebla',
    country: 'México',
    description: 'Puebla en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/VZcb6neiihI${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-volcan-colima',
    name: 'Volcán de Colima',
    city: 'Colima',
    country: 'México',
    description: 'Volcán de Colima en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/hKj918yyq10${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cozumel-quintana-roo',
    name: 'Cozumel, Quintana Roo',
    city: 'Cozumel',
    country: 'México',
    description: 'Cozumel, Quintana Roo en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OcS0DxGKjG4${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-mazatlan-sinaloa',
    name: 'Mazatlán, Sinaloa',
    city: 'Mazatlán',
    country: 'México',
    description: 'Mazatlán, Sinaloa en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/SWHJFE29Bo0${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cancun-poniente',
    name: 'Cancún, Quintana Roo hacia el Poniente',
    city: 'Cancún',
    country: 'México',
    description: 'Cancún hacia el poniente en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/AyVSlOI7c9Q${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-torre-latino-este',
    name: 'CDMX Torre Latino Este',
    city: 'CDMX',
    country: 'México',
    description: 'Vista este desde la Torre Latinoamericana',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/J0_rtFPD-oE${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-chapultepec',
    name: 'CDMX Bosque de Chapultepec',
    city: 'CDMX',
    country: 'México',
    description: 'Bosque de Chapultepec en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/SEmWKejE2Xg${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-tlalpan',
    name: 'CDMX, Centro Tlalpan',
    city: 'CDMX',
    country: 'México',
    description: 'Centro de Tlalpan en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/EaBdl4I887c${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-volcan-colima-palmillas',
    name: 'Volcán de Colima desde Palmillas',
    city: 'Colima',
    country: 'México',
    description: 'Volcán de Colima visto desde Palmillas',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/oC11QNM--hY${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-popo-amecameca',
    name: 'Volcán Popocatépetl desde Amecameca',
    city: 'Amecameca',
    country: 'México',
    description: 'Popocatépetl visto desde Amecameca',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/URhVB0yqOoc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-queretaro-panoramica',
    name: 'Querétaro, Panorámica',
    city: 'Querétaro',
    country: 'México',
    description: 'Vista panorámica de Querétaro',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/x1chHm_9HfA${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-tijuana-panoramica',
    name: 'Tijuana, Vista Panorámica',
    city: 'Tijuana',
    country: 'México',
    description: 'Vista panorámica de Tijuana',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/WcBxvZKxftM${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cancun-nichupte',
    name: 'Cancún, Laguna de Nichupté',
    city: 'Cancún',
    country: 'México',
    description: 'Laguna de Nichupté, Cancún en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/sV1FnrIukbQ${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-teotihuacan',
    name: 'Pirámides de Teotihuacán',
    city: 'Teotihuacán',
    country: 'México',
    description: 'Pirámides de Teotihuacán en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/QDDJabSPu70${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-hermosillo-panoramica',
    name: 'Hermosillo, Son. Panorámica',
    city: 'Hermosillo',
    country: 'México',
    description: 'Vista panorámica de Hermosillo, Sonora',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/z_I152IMqI8${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'sky-cabo-san-lucas',
    name: 'Cabo San Lucas, BCS',
    city: 'Cabo San Lucas',
    country: 'México',
    description: 'Cabo San Lucas en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/mexico/baja-california-sur/cabo-san-lucas/cabo-san-lucas.html',
    region: 'mexico',
  },
  {
    id: 'sky-xcaret-qroo',
    name: 'Xcaret, Quintana Roo',
    city: 'Playa del Carmen',
    country: 'México',
    description: 'Parque Xcaret en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/mexico/quintana-roo/solidaridad/el-parque-de-xcaret.html',
    region: 'mexico',
  },
  // ═══════════════════════════════════════
  // Norteamérica
  // ═══════════════════════════════════════
  {
    id: 'yt-times-square',
    name: 'Times Square, NY',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Times Square en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/rnXIjl_Rzy4${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-manhattan-broadway',
    name: 'Manhattan Broadway, NY',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Manhattan Broadway en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/4qyZLflp-sI${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-lower-manhattan',
    name: 'Lower Manhattan, NY',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Lower Manhattan en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/MKJnCn2C1MI${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-brooklyn-bridge',
    name: 'Brooklyn Bridge, NY',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Brooklyn Bridge en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/A_ayQypqxEU${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-nyc-harbor',
    name: 'New York City Harbor',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Puerto de Nueva York en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OgqbZLzEbQU${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-washington-dc',
    name: 'Washington D.C.',
    city: 'Washington D.C.',
    country: 'EE.UU.',
    description: 'Washington D.C. en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/1wV9lLe14aU${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-white-house',
    name: 'White House, Washington D.C.',
    city: 'Washington D.C.',
    country: 'EE.UU.',
    description: 'Casa Blanca en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/Fu8vYoIkaeM${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-bryant-park',
    name: 'Bryant Park, New York',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Bryant Park en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/XDgu2VKXM3s${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-venice-beach',
    name: 'Venice Beach, CA',
    city: 'Los Ángeles',
    country: 'EE.UU.',
    description: 'Venice Beach en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/EO_1LWqsCNE${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'yt-san-diego-ca',
    name: 'San Diego, CA',
    city: 'San Diego',
    country: 'EE.UU.',
    description: 'San Diego, California en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/edz0ux7JClE${YT_PARAMS}`,
    region: 'northamerica',
  },
  // ═══════════════════════════════════════
  // Canadá
  // ═══════════════════════════════════════
  {
    id: 'sky-toronto',
    name: 'Toronto, Canadá',
    city: 'Toronto',
    country: 'Canadá',
    description: 'Toronto CN Tower en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/canada/ontario/toronto/ytz-cn-tower.html',
    region: 'northamerica',
  },
  {
    id: 'sky-niagara-falls',
    name: 'Niagara Falls, Canadá',
    city: 'Niagara Falls',
    country: 'Canadá',
    description: 'Cataratas del Niágara en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/canada/ontario/niagara-falls/niagara-falls.html',
    region: 'northamerica',
  },
  {
    id: 'yt-ottawa-canada',
    name: 'Ottawa, Canadá',
    city: 'Ottawa',
    country: 'Canadá',
    description: 'Ottawa en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/lLYosWv_AwQ${YT_PARAMS}`,
    region: 'northamerica',
  },
  {
    id: 'sky-vancouver',
    name: 'Vancouver, Canadá',
    city: 'Vancouver',
    country: 'Canadá',
    description: 'Panorámica de Vancouver en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/canada/british-columbia/vancouver/panorama.html',
    region: 'northamerica',
  },
  // ═══════════════════════════════════════
  // Europa
  // ═══════════════════════════════════════
  {
    id: 'yt-paris',
    name: 'París, Francia',
    city: 'París',
    country: 'Francia',
    description: 'París en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/OzYp4NRZlwQ${YT_PARAMS}`,
    region: 'europe',
  },
  {
    id: 'sky-puerta-sol-madrid',
    name: 'Puerta del Sol, Madrid',
    city: 'Madrid',
    country: 'España',
    description: 'Puerta del Sol en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/puerta-del-sol-tio-pepe.html',
    region: 'europe',
  },
  {
    id: 'sky-plaza-callao-madrid',
    name: 'Plaza del Callao, Madrid',
    city: 'Madrid',
    country: 'España',
    description: 'Plaza del Callao en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/madrid-plaza-del-callao.html',
    region: 'europe',
  },
  {
    id: 'sky-calle-alcala-madrid',
    name: 'Calle Alcalá, Madrid',
    city: 'Madrid',
    country: 'España',
    description: 'Calle Alcalá en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/espana/comunidad-de-madrid/madrid/calle-alcala.html',
    region: 'europe',
  },
  {
    id: 'sky-alhambra-granada',
    name: 'Alhambra, Granada',
    city: 'Granada',
    country: 'España',
    description: 'Alhambra de Granada en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/espana/andalucia/granada/alhambra-de-granada.html',
    region: 'europe',
  },
  {
    id: 'sky-barcelona-playa',
    name: 'Playa San Sebastián, Barcelona',
    city: 'Barcelona',
    country: 'España',
    description: 'Playa Sant Sebastià en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/espana/cataluna/barcelona/playa-sant-sebastia.html',
    region: 'europe',
  },
  {
    id: 'sky-coliseo-roma',
    name: 'Coliseo, Roma',
    city: 'Roma',
    country: 'Italia',
    description: 'Coliseo de Roma en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/italia/lazio/roma/roma-colosseo.html',
    region: 'europe',
  },
  {
    id: 'sky-florencia-duomo',
    name: 'Florencia, Piazza del Duomo',
    city: 'Florencia',
    country: 'Italia',
    description: 'Piazza del Duomo, Florencia en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/italia/toscana/firenze/piazza-duomo-firenze.html',
    region: 'europe',
  },
  {
    id: 'yt-estambul',
    name: 'Estambul, Turquía',
    city: 'Estambul',
    country: 'Turquía',
    description: 'Estambul en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/VdAUx5pV3A4${YT_PARAMS}`,
    region: 'europe',
  },
  // ═══════════════════════════════════════
  // Asia y Medio Oriente
  // ═══════════════════════════════════════
  {
    id: 'yt-tokyo',
    name: 'Tokio, Japón',
    city: 'Tokio',
    country: 'Japón',
    description: 'Tokio en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/_k-5U7IeK8g${YT_PARAMS}`,
    region: 'asia_mideast',
  },
  {
    id: 'yt-tokyo-odaiba',
    name: 'Tokio, Odaiba',
    city: 'Tokio',
    country: 'Japón',
    description: 'Odaiba, Tokio en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/ytXE2pk07dA${YT_PARAMS}`,
    region: 'asia_mideast',
  },
  {
    id: 'yt-hong-kong',
    name: 'Hong Kong, China',
    city: 'Hong Kong',
    country: 'China',
    description: 'Hong Kong en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/eaHSUjbK75o${YT_PARAMS}`,
    region: 'asia_mideast',
  },
  {
    id: 'sky-piramide-giza',
    name: 'Pirámide de Guiza, Egipto',
    city: 'El Cairo',
    country: 'Egipto',
    description: 'Gran Pirámide de Guiza en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/egypt/cairo/cairo/great-pyramid-of-giza.html',
    region: 'asia_mideast',
  },
  // ═══════════════════════════════════════
  // América Latina
  // ═══════════════════════════════════════
  {
    id: 'sky-miraflores-lima',
    name: 'Miraflores, Lima',
    city: 'Lima',
    country: 'Perú',
    description: 'Panorámica de Miraflores en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/peru/lima/lima/panoramica-de-miraflores.html',
    region: 'latam',
  },
  {
    id: 'sky-obelisco-buenosaires',
    name: 'Obelisco, Buenos Aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    description: 'Obelisco de Buenos Aires en vivo',
    sourceType: 'skylinewebcams',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/argentina/buenos-aires/buenos-aires/obelisco.html',
    region: 'latam',
  },
  // ═══════════════════════════════════════
  // Global
  // ═══════════════════════════════════════
  {
    id: 'yt-earthquake-monitor',
    name: 'LIVE Earthquake Monitor',
    city: 'Global',
    country: 'Global',
    description: 'Monitor de sismos en tiempo real',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/rvtygG4n6ew${YT_PARAMS}`,
    region: 'northamerica',
  },
];

// IDs de las 4 cámaras por defecto al abrir por primera vez
export const DEFAULT_INITIAL_CAMERA_IDS = [
  'yt-cdmx-torre-latino-sur',
  'yt-cdmx-torre-latino-poniente',
  'yt-bellas-artes',
  'yt-cdmx-zocalo2',
];

export const LAYOUT_OPTIONS: LayoutOption[] = [
  { type: '1x1', label: '1×1', cells: 1, icon: '⬜' },
  { type: '2x1', label: '2×1', cells: 2, icon: '▬' },
  { type: '2x2', label: '2×2', cells: 4, icon: '⊞' },
  { type: '1+2', label: '1+2', cells: 3, icon: '◧' },
  { type: '1+4', label: '1+4', cells: 5, icon: '◫' },
  { type: '3x3', label: '3×3', cells: 9, icon: '▦' },
];

export function getCellCount(layout: string): number {
  return LAYOUT_OPTIONS.find(l => l.type === layout)?.cells ?? 4;
}

export const REGION_LABELS: Record<string, string> = {
  mexico: '🇲🇽 México',
  latam: '🌎 América Latina',
  northamerica: '🇺🇸 Norteamérica',
  europe: '🇪🇺 Europa',
  asia_mideast: '🌏 Asia y Medio Oriente',
};
