// Catálogo de cámaras verificadas — v2
// Fuentes: YouTube, SkylineWebcams, EarthTV, WebcamsDeMexico, URLs externas
// Última actualización: marzo 2026

import { Camera, LayoutOption } from './types';

const YT_PARAMS = '?autoplay=1&mute=1&controls=0&modestbranding=1&rel=0&iv_load_policy=3&playsinline=1';

export const DEFAULT_CAMERAS: Camera[] = [
  // ═══════════════════════════════════════
  // TIPO A: YouTube
  // ═══════════════════════════════════════
  {
    id: 'yt-cdmx-ref',
    name: 'CDMX - Cámara en vivo',
    city: 'CDMX',
    country: 'México',
    description: 'Ciudad de México en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/yyWbHA_EWCc${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-reforma',
    name: 'CDMX - Paseo de la Reforma',
    city: 'CDMX',
    country: 'México',
    description: 'Paseo de la Reforma en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/GfAyEuypRDI${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-cdmx-aeropuerto',
    name: 'CDMX - Aeropuerto / Tráfico',
    city: 'CDMX',
    country: 'México',
    description: 'Vista aérea CDMX en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/NI4v1OlIlZM${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-popocatepetl-live',
    name: 'Popocatépetl - En vivo',
    city: 'Popocatépetl',
    country: 'México',
    description: 'Volcán Popocatépetl en vivo',
    sourceType: 'youtube',
    embedUrl: `https://www.youtube.com/embed/9f3npaKdyCA${YT_PARAMS}`,
    region: 'mexico',
  },
  {
    id: 'yt-popocatepetl-afartv',
    name: 'Popocatépetl 4K - AfarTV',
    city: 'Popocatépetl',
    country: 'México',
    description: 'Volcán en vivo 4K — canal @afartv',
    sourceType: 'youtube_channel',
    embedUrl: `https://www.youtube.com/embed/live_stream?channel=UCaG0IHN1RMOZ4-U3wDXAkwA${YT_PARAMS.replace('?', '&')}`,
    region: 'mexico',
  },

  // ═══════════════════════════════════════
  // TIPO B: SkylineWebcams
  // ═══════════════════════════════════════
  {
    id: 'sky-cdmx-zocalo',
    name: 'CDMX - Zócalo',
    city: 'CDMX',
    country: 'México',
    description: 'Zócalo vía SkylineWebcams',
    sourceType: 'skylinewebcams',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/mexico/federal-district/mexico-city/zocalo.html',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/mexico/federal-district/mexico-city/zocalo.html',
    region: 'mexico',
  },
  {
    id: 'sky-cdmx-vista',
    name: 'CDMX - Vista General',
    city: 'CDMX',
    country: 'México',
    description: 'Vista general CDMX vía SkylineWebcams',
    sourceType: 'skylinewebcams',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/mexico/federal-district/mexico-city/mexico-city.html',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/mexico/federal-district/mexico-city/mexico-city.html',
    region: 'mexico',
  },
  {
    id: 'sky-gdl',
    name: 'Guadalajara - Panorámica',
    city: 'Guadalajara',
    country: 'México',
    description: 'Vista panorámica vía SkylineWebcams',
    sourceType: 'skylinewebcams',
    embedUrl: 'https://www.skylinewebcams.com/es/webcam/mexico/jalisco/guadalajara.html',
    externalUrl: 'https://www.skylinewebcams.com/es/webcam/mexico/jalisco/guadalajara.html',
    region: 'mexico',
  },
  {
    id: 'sky-mty',
    name: 'Monterrey - Panorama',
    city: 'Monterrey',
    country: 'México',
    description: 'Panorama vía SkylineWebcams',
    sourceType: 'skylinewebcams',
    embedUrl: 'https://www.skylinewebcams.com/es/webcam/mexico/nuevo-leon/monterrey/panorama.html',
    externalUrl: 'https://www.skylinewebcams.com/es/webcam/mexico/nuevo-leon/monterrey/panorama.html',
    region: 'mexico',
  },
  {
    id: 'sky-madrid',
    name: 'Madrid',
    city: 'Madrid',
    country: 'España',
    description: 'Vista ciudad vía SkylineWebcams',
    sourceType: 'skylinewebcams',
    embedUrl: 'https://www.skylinewebcams.com/es/webcam/espana/comunidad-de-madrid/madrid.html',
    externalUrl: 'https://www.skylinewebcams.com/es/webcam/espana/comunidad-de-madrid/madrid.html',
    region: 'europe',
  },
  {
    id: 'sky-paris',
    name: 'París - Torre Eiffel',
    city: 'París',
    country: 'Francia',
    description: 'Torre Eiffel vía SkylineWebcams',
    sourceType: 'skylinewebcams',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/france/ile-de-france/paris/tour-eiffel.html',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/france/ile-de-france/paris/tour-eiffel.html',
    region: 'europe',
  },
  {
    id: 'sky-tokyo',
    name: 'Tokio - Shibuya Crossing',
    city: 'Tokio',
    country: 'Japón',
    description: 'Shibuya Crossing vía SkylineWebcams',
    sourceType: 'skylinewebcams',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/japan/kanto/tokyo/tokyo-shibuya-scramble-crossing.html',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/japan/kanto/tokyo/tokyo-shibuya-scramble-crossing.html',
    region: 'asia_mideast',
  },
  {
    id: 'sky-nyc',
    name: 'Nueva York - Times Square',
    city: 'Nueva York',
    country: 'EE.UU.',
    description: 'Times Square vía SkylineWebcams',
    sourceType: 'skylinewebcams',
    embedUrl: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/new-york-city.html',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/new-york-city.html',
    region: 'northamerica',
  },

  // ═══════════════════════════════════════
  // TIPO C: EarthTV
  // ═══════════════════════════════════════
  {
    id: 'earth-cdmx-alameda',
    name: 'CDMX - Alameda Central',
    city: 'CDMX',
    country: 'México',
    description: 'Alameda Central / Torre Latinoamericana vía EarthTV',
    sourceType: 'earthtv',
    embedUrl: 'https://www.earthtv.com/en/webcam/mexico-city-alameda-central/live-stream',
    externalUrl: 'https://www.earthtv.com/en/webcam/mexico-city-alameda-central',
    region: 'mexico',
  },
  {
    id: 'earth-gdl-minerva',
    name: 'Guadalajara - Glorieta Minerva',
    city: 'Guadalajara',
    country: 'México',
    description: 'Glorieta Minerva vía EarthTV',
    sourceType: 'earthtv',
    embedUrl: 'https://www.earthtv.com/en/webcam/guadalajara-minerva-roundabout/live-stream',
    externalUrl: 'https://www.earthtv.com/en/webcam/guadalajara-minerva-roundabout',
    region: 'mexico',
  },
  {
    id: 'earth-paris',
    name: 'París - Torre Eiffel (Peninsula)',
    city: 'París',
    country: 'Francia',
    description: 'Torre Eiffel desde Peninsula Hotel vía EarthTV',
    sourceType: 'earthtv',
    embedUrl: 'https://www.earthtv.com/en/webcam/paris-eiffel-tower/live-stream',
    externalUrl: 'https://www.earthtv.com/en/webcam/paris-eiffel-tower',
    region: 'europe',
  },

  // ═══════════════════════════════════════
  // TIPO D: Webcams de México
  // ═══════════════════════════════════════
  {
    id: 'wcm-cdmx-zocalo',
    name: 'CDMX - Zócalo Gran Hotel',
    city: 'CDMX',
    country: 'México',
    description: 'Zócalo Gran Hotel vía webcamsdemexico.com',
    sourceType: 'webcamsdemexico',
    embedUrl: 'https://webcamsdemexico.com/webcam/mexico-zocalo/',
    externalUrl: 'https://webcamsdemexico.com/webcam/mexico-zocalo/',
    region: 'mexico',
  },
  {
    id: 'wcm-cdmx-zocalo-zoom',
    name: 'CDMX - Zócalo Zoom',
    city: 'CDMX',
    country: 'México',
    description: 'Zócalo zoom vía webcamsdemexico.com',
    sourceType: 'webcamsdemexico',
    embedUrl: 'https://webcamsdemexico.com/webcam/zocalo-zoom/',
    externalUrl: 'https://webcamsdemexico.com/webcam/zocalo-zoom/',
    region: 'mexico',
  },
  {
    id: 'wcm-popo-altzomoni',
    name: 'Popocatépetl - Altzomoni',
    city: 'Popocatépetl',
    country: 'México',
    description: 'Vista desde Altzomoni vía webcamsdemexico.com',
    sourceType: 'webcamsdemexico',
    embedUrl: 'https://webcamsdemexico.com/webcam/popocatepetl-altzomoni/',
    externalUrl: 'https://webcamsdemexico.com/webcam/popocatepetl-altzomoni/',
    region: 'mexico',
  },

  // ═══════════════════════════════════════
  // TIPO E: Solo URL externo (placeholder + botón "Ver en vivo")
  // ═══════════════════════════════════════
  {
    id: 'ext-culiacan',
    name: 'Culiacán',
    city: 'Culiacán',
    country: 'México',
    description: 'Webcam vía Pictimo',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://www.pictimo.com/country/mexico',
    region: 'mexico',
  },
  {
    id: 'ext-acapulco',
    name: 'Acapulco',
    city: 'Acapulco',
    country: 'México',
    description: 'Webcam vía WebcamTaxi',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://www.webcamtaxi.com/en/mexico/guerrero.html',
    region: 'mexico',
  },
  {
    id: 'ext-puebla',
    name: 'Puebla',
    city: 'Puebla',
    country: 'México',
    description: 'Vista Holiday Inn Puebla',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://balticlivecam.com/cameras/mexico/puebla/view-holiday-inn-puebla/',
    region: 'mexico',
  },
  {
    id: 'ext-la',
    name: 'Los Ángeles',
    city: 'Los Ángeles',
    country: 'EE.UU.',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/united-states/los-angeles/',
    region: 'northamerica',
  },
  {
    id: 'ext-miami',
    name: 'Miami',
    city: 'Miami',
    country: 'EE.UU.',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/united-states/miami/',
    region: 'northamerica',
  },
  {
    id: 'ext-dc',
    name: 'Washington D.C.',
    city: 'Washington D.C.',
    country: 'EE.UU.',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/united-states/washington/',
    region: 'northamerica',
  },
  {
    id: 'ext-bogota',
    name: 'Bogotá',
    city: 'Bogotá',
    country: 'Colombia',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/colombia/bogota/',
    region: 'latam',
  },
  {
    id: 'ext-medellin',
    name: 'Medellín',
    city: 'Medellín',
    country: 'Colombia',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/colombia/medellin/',
    region: 'latam',
  },
  {
    id: 'ext-lima',
    name: 'Lima',
    city: 'Lima',
    country: 'Perú',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/peru/lima/',
    region: 'latam',
  },
  {
    id: 'ext-buenosaires',
    name: 'Buenos Aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/argentina/buenos-aires/',
    region: 'latam',
  },
  {
    id: 'ext-panama',
    name: 'Ciudad de Panamá',
    city: 'Ciudad de Panamá',
    country: 'Panamá',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/panama/panama-city/',
    region: 'latam',
  },
  {
    id: 'ext-abudhabi',
    name: 'Abu Dhabi',
    city: 'Abu Dhabi',
    country: 'EAU',
    description: 'Webcam vía SkylineWebcams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://www.skylinewebcams.com/en/webcam/united-arab-emirates.html',
    region: 'asia_mideast',
  },
  {
    id: 'ext-dubai',
    name: 'Dubái',
    city: 'Dubái',
    country: 'EAU',
    description: 'Webcam vía WorldCams',
    sourceType: 'external_url',
    embedUrl: '',
    externalUrl: 'https://worldcams.tv/united-arab-emirates/dubai/',
    region: 'asia_mideast',
  },
];

// IDs de las 4 cámaras por defecto al abrir por primera vez
export const DEFAULT_INITIAL_CAMERA_IDS = [
  'wcm-cdmx-zocalo',        // Celda 1: Zócalo Gran Hotel
  'sky-cdmx-vista',          // Celda 2: Vista general CDMX
  'earth-cdmx-alameda',     // Celda 3: Alameda Central / Torre Latino
  'yt-popocatepetl-afartv',  // Celda 4: Popocatépetl 4K AfarTV
];

export const LAYOUT_OPTIONS: LayoutOption[] = [
  { type: '1x1', label: '1×1', cells: 1, icon: '⬜' },
  { type: '2x1', label: '2×1', cells: 2, icon: '▬' },
  { type: '2x2', label: '2×2', cells: 4, icon: '⊞' },
  { type: '1+2', label: '1+2', cells: 3, icon: '◧' },
  { type: '1+4', label: '1+4', cells: 5, icon: '◫' },
  { type: '3x3', label: '3×3', cells: 9, icon: '▦' },
];

export function getCellCount(layout: string): number {
  return LAYOUT_OPTIONS.find(l => l.type === layout)?.cells ?? 4;
}

// Agrupar cámaras por región para la biblioteca
export const REGION_LABELS: Record<string, string> = {
  mexico: '🇲🇽 México',
  latam: '🌎 América Latina',
  northamerica: '🇺🇸 Norteamérica',
  europe: '🇪🇺 Europa',
  asia_mideast: '🌏 Asia y Medio Oriente',
};
