// Hook to manage Web Push subscription registration with real VAPID keys
import { useState, useEffect, useCallback, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from './useAuth';
import { toast } from 'sonner';
import { playMessageNotification } from '@/lib/alertSound';

// VAPID Public Key - must match the one in Cloud secrets
// This is the public key generated by the user
const VAPID_PUBLIC_KEY = 'BOhw5PII8GJuBb9hLaU2yPpIZ9nejYv7tRiRFP1B7rMSr9CTlLVu9Cm5GHQOQaFU7asSRrdruOcRqYRl4LM8LOw';

interface PushSubscriptionState {
  isSupported: boolean;
  isSubscribed: boolean;
  permission: NotificationPermission | 'unsupported';
  registration: ServiceWorkerRegistration | null;
}

// Convert base64 URL to Uint8Array for VAPID key
function urlBase64ToUint8Array(base64String: string): ArrayBuffer {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray.buffer as ArrayBuffer;
}

// Show browser notification
function showNotification(title: string, body: string, data?: Record<string, unknown>) {
  if (Notification.permission === 'granted') {
    const notification = new Notification(title, {
      body,
      icon: '/icon-192.png',
      badge: '/icon-192.png',
      tag: 'mats-message',
      data,
    });
    
    notification.onclick = () => {
      window.focus();
      notification.close();
    };
  }
}

export function useWebPushSubscription() {
  const { user } = useAuth();
  const channelRef = useRef<ReturnType<typeof supabase.channel> | null>(null);
  const [state, setState] = useState<PushSubscriptionState>({
    isSupported: false,
    isSubscribed: false,
    permission: 'default',
    registration: null,
  });

  // Check if Web Push is supported and get existing subscription
  useEffect(() => {
    async function checkSupport() {
      const isSupported = 
        'serviceWorker' in navigator && 
        'PushManager' in window && 
        'Notification' in window;

      if (!isSupported) {
        setState(prev => ({ ...prev, isSupported: false, permission: 'unsupported' }));
        return;
      }

      const permission = Notification.permission;
      
      try {
        const registration = await navigator.serviceWorker.ready;
        const subscription = await (registration as any).pushManager.getSubscription();
        
        setState({
          isSupported: true,
          isSubscribed: !!subscription,
          permission,
          registration,
        });
      } catch (error) {
        console.error('[WebPush] Error checking subscription:', error);
        setState(prev => ({ 
          ...prev, 
          isSupported: true, 
          permission 
        }));
      }
    }

    checkSupport();
  }, []);

  // Save subscription to database
  const saveSubscription = useCallback(async (subscription: PushSubscription): Promise<boolean> => {
    if (!user?.id) return false;

    const key = subscription.getKey('p256dh');
    const auth = subscription.getKey('auth');

    if (!key || !auth) {
      console.error('[WebPush] Missing p256dh or auth keys');
      return false;
    }

    const p256dh = btoa(String.fromCharCode(...new Uint8Array(key)));
    const authKey = btoa(String.fromCharCode(...new Uint8Array(auth)));

    try {
      // Check if subscription already exists
      const { data: existing } = await supabase
        .from('push_subscriptions')
        .select('id')
        .eq('user_id', user.id)
        .eq('endpoint', subscription.endpoint)
        .maybeSingle();

      if (existing) {
        // Update existing subscription
        const { error } = await supabase
          .from('push_subscriptions')
          .update({
            p256dh,
            auth: authKey,
            updated_at: new Date().toISOString(),
          })
          .eq('id', existing.id);

        if (error) throw error;
      } else {
        // Insert new subscription
        const { error } = await supabase
          .from('push_subscriptions')
          .insert({
            user_id: user.id,
            endpoint: subscription.endpoint,
            p256dh,
            auth: authKey,
          });

        if (error) throw error;
      }

      console.log('[WebPush] Subscription saved to database');
      return true;
    } catch (error) {
      console.error('[WebPush] Error saving subscription:', error);
      return false;
    }
  }, [user?.id]);

  // Subscribe to realtime broadcast channel as fallback (for when app is in foreground)
  useEffect(() => {
    if (!user?.id || !state.isSupported) return;

    // Create a unique channel for this user to receive message notifications
    const channel = supabase
      .channel(`user-notifications:${user.id}`)
      .on('broadcast', { event: 'new_message' }, (payload) => {
        console.log('[Push] Received broadcast notification:', payload);
        const { senderName, messagePreview } = payload.payload as { senderName: string; messagePreview: string };
        
        // Play the notification sound if not muted
        const muted = localStorage.getItem('chat_notifications_muted') === 'true';
        if (!muted) {
          playMessageNotification();
        }
        
        // Show notification if tab is not focused
        if (document.hidden && Notification.permission === 'granted') {
          showNotification(`💬 Mensaje de ${senderName}`, messagePreview || 'Tienes un nuevo mensaje');
        } else if (document.hidden) {
          // Fallback to toast if notifications not granted
          toast.info(`💬 ${senderName}`, { description: messagePreview || 'Nuevo mensaje' });
        }
      })
      .subscribe((status) => {
        console.log('[Push] Broadcast channel status:', status);
      });

    channelRef.current = channel;

    return () => {
      if (channelRef.current) {
        supabase.removeChannel(channelRef.current);
        channelRef.current = null;
      }
    };
  }, [user?.id, state.isSupported]);

  // Subscribe to Web Push notifications (with VAPID)
  const subscribe = useCallback(async (): Promise<boolean> => {
    if (!state.isSupported || !state.registration) {
      console.warn('[WebPush] Push not supported');
      return false;
    }

    try {
      // Request notification permission
      const permission = await Notification.requestPermission();
      setState(prev => ({ ...prev, permission }));

      if (permission !== 'granted') {
        console.log('[WebPush] Permission denied');
        return false;
      }

      // Check for existing subscription
      let subscription = await (state.registration as any).pushManager.getSubscription();
      
      // If no subscription or VAPID key changed, create new one
      if (!subscription) {
        try {
          subscription = await (state.registration as any).pushManager.subscribe({
            userVisibleOnly: true,
            applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
          });
          console.log('[WebPush] New subscription created:', subscription.endpoint);
        } catch (subscribeError) {
          console.error('[WebPush] Subscribe error:', subscribeError);
          // Fallback: still mark as subscribed for broadcast fallback
          setState(prev => ({ ...prev, isSubscribed: true }));
          return true;
        }
      }

      // Save to database
      const saved = await saveSubscription(subscription);
      
      setState(prev => ({ ...prev, isSubscribed: true }));
      console.log('[WebPush] Subscription active');
      return saved;
    } catch (error) {
      console.error('[WebPush] Subscribe error:', error);
      return false;
    }
  }, [state.isSupported, state.registration, saveSubscription]);

  // Unsubscribe from notifications
  const unsubscribe = useCallback(async (): Promise<boolean> => {
    if (!state.registration) return false;

    try {
      const subscription = await (state.registration as any).pushManager.getSubscription();
      
      if (subscription) {
        // Remove from database
        if (user?.id) {
          await supabase
            .from('push_subscriptions')
            .delete()
            .eq('user_id', user.id)
            .eq('endpoint', subscription.endpoint);
        }

        // Unsubscribe from push manager
        await subscription.unsubscribe();
      }

      if (channelRef.current) {
        supabase.removeChannel(channelRef.current);
        channelRef.current = null;
      }
      
      setState(prev => ({ ...prev, isSubscribed: false }));
      return true;
    } catch (error) {
      console.error('[WebPush] Unsubscribe error:', error);
      return false;
    }
  }, [state.registration, user?.id]);

  // Auto-subscribe when user logs in and permission was previously granted
  useEffect(() => {
    if (
      user?.id && 
      state.isSupported && 
      state.permission === 'granted' && 
      !state.isSubscribed && 
      state.registration
    ) {
      // Auto-resubscribe silently
      (state.registration as any).pushManager.getSubscription().then(async (existingSub: any) => {
        if (existingSub) {
          await saveSubscription(existingSub);
          setState(prev => ({ ...prev, isSubscribed: true }));
        } else {
          // Try to create new subscription
          try {
            const subscription = await (state.registration as any).pushManager.subscribe({
              userVisibleOnly: true,
              applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
            });
            await saveSubscription(subscription);
            setState(prev => ({ ...prev, isSubscribed: true }));
          } catch (e) {
            console.warn('[WebPush] Auto-subscribe failed:', e);
            // Still mark as subscribed for broadcast fallback
            setState(prev => ({ ...prev, isSubscribed: true }));
          }
        }
      });
    }
  }, [user?.id, state.isSupported, state.permission, state.isSubscribed, state.registration, saveSubscription]);

  // Force push subscription prompt for emergency app - show toast if not subscribed
  useEffect(() => {
    // Only run after initial check is complete and user is logged in
    if (!user?.id || !state.isSupported || !state.registration) return;
    
    // Check if we've already shown the prompt recently (avoid spamming)
    const lastPromptTime = localStorage.getItem('push_prompt_shown_at');
    const now = Date.now();
    const ONE_DAY = 24 * 60 * 60 * 1000;
    
    if (lastPromptTime && (now - parseInt(lastPromptTime, 10)) < ONE_DAY) {
      return; // Don't show again within 24 hours
    }

    // After a short delay, check if push is not active and prompt user
    const timer = setTimeout(async () => {
      // Re-check current subscription status
      try {
        const currentSub = await (state.registration as any)?.pushManager.getSubscription();
        
        if (!currentSub && state.permission !== 'denied') {
          // User doesn't have push subscription - this is critical for emergency app
          console.log('[WebPush] No push subscription found - prompting user');
          localStorage.setItem('push_prompt_shown_at', now.toString());
          
          toast.warning('⚠️ Notificaciones Push NO activas', {
            description: 'Por tu seguridad, activa las notificaciones push en Ajustes para recibir alertas de emergencia.',
            duration: 10000,
            action: {
              label: 'Ir a Ajustes',
              onClick: () => {
                // This will be handled by parent component
                window.dispatchEvent(new CustomEvent('open-settings-for-push'));
              },
            },
          });
        }
      } catch (err) {
        console.warn('[WebPush] Error checking subscription for prompt:', err);
      }
    }, 5000); // Wait 5 seconds after app load

    return () => clearTimeout(timer);
  }, [user?.id, state.isSupported, state.permission, state.registration]);

  return {
    isSupported: state.isSupported,
    isSubscribed: state.isSubscribed,
    permission: state.permission,
    subscribe,
    unsubscribe,
  };
}
